project:
  type: website
  render:
        - "*.qmd"  # render all other .qmd files
        - "!time_series_analysis.qmd" 

website:
  title: "DSAN 5100 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: Exploratory Data Analysis
      - href: report.qmd
        text: Project Report
      - href: hypothesis_testing.qmd
        text: Hypothesis Testing
      - href: time_series.qmd
        text: Time Series Analysis
      - about.qmd

format:
  html:
    theme: styles.scss
    # css: styles.css
    toc: true
    toc-location: left
    code-fold: true
    code-summary: "Click to see code"

bibliography: references.bib
