project:
  type: website

website:
  title: "DSAN 5100 Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: Exploratory Data Analysis
      - href: report.qmd
        text: Project Report
      - about.qmd

format:
  html:
    theme: styles.scss
    # css: styles.css
    toc: true
    toc-location: left

bibliography: references.bib
