project:
  type: website

website:
  title: "5100-project-website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: Exploratory Data Analysis
      - href: report.qmd
        text: Project Report
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



